Traceback (most recent call last):
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/victorgallego/miniforge3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
image_url = "https://pbs.twimg.com/media/FrSGyS9WIAMLGbe?format=jpg&name=small"
prompt = "Describe what is in this photo"

response = compute_response(image_url, prompt)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAuthenticationError[0m                       Traceback (most recent call last)
[0;32m/var/folders/l_/k13w4mhd5hv4bddxwqz8qdfw0000gn/T/ipykernel_6579/2312586773.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mprompt[0m [0;34m=[0m [0;34m"Describe what is in this photo"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[0;32m----> 4[0;31m [0mresponse[0m [0;34m=[0m [0mcompute_response[0m[0;34m([0m[0mimage_url[0m[0;34m,[0m [0mprompt[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/var/folders/l_/k13w4mhd5hv4bddxwqz8qdfw0000gn/T/ipykernel_6579/2882202318.py[0m in [0;36mcompute_response[0;34m(image_url, prompt)[0m
[1;32m      1[0m [0;32mdef[0m [0mcompute_response[0m[0;34m([0m[0mimage_url[0m[0;34m,[0m [0mprompt[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     response = client.chat.completions.create(
[0m[1;32m      3[0m         [0mmodel[0m[0;34m=[0m[0;34m"gpt-4-vision-preview"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m         messages=[
[1;32m      5[0m             {

[0;32m~/miniforge3/lib/python3.9/site-packages/openai/_utils/_utils.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m    297[0m                         [0mmsg[0m [0;34m=[0m [0;34mf"Missing required argument: {quote(missing[0])}"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    298[0m                 [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 299[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    300[0m [0;34m[0m[0m
[1;32m    301[0m         [0;32mreturn[0m [0mwrapper[0m  [0;31m# type: ignore[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/openai/resources/chat/completions.py[0m in [0;36mcreate[0;34m(self, messages, model, frequency_penalty, function_call, functions, logit_bias, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_p, user, extra_headers, extra_query, extra_body, timeout)[0m
[1;32m    596[0m         [0mtimeout[0m[0;34m:[0m [0mfloat[0m [0;34m|[0m [0mhttpx[0m[0;34m.[0m[0mTimeout[0m [0;34m|[0m [0;32mNone[0m [0;34m|[0m [0mNotGiven[0m [0;34m=[0m [0mNOT_GIVEN[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    597[0m     ) -> ChatCompletion | Stream[ChatCompletionChunk]:
[0;32m--> 598[0;31m         return self._post(
[0m[1;32m    599[0m             [0;34m"/chat/completions"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    600[0m             body=maybe_transform(

[0;32m~/miniforge3/lib/python3.9/site-packages/openai/_base_client.py[0m in [0;36mpost[0;34m(self, path, cast_to, body, options, files, stream, stream_cls)[0m
[1;32m   1061[0m             [0mmethod[0m[0;34m=[0m[0;34m"post"[0m[0;34m,[0m [0murl[0m[0;34m=[0m[0mpath[0m[0;34m,[0m [0mjson_data[0m[0;34m=[0m[0mbody[0m[0;34m,[0m [0mfiles[0m[0;34m=[0m[0mto_httpx_files[0m[0;34m([0m[0mfiles[0m[0;34m)[0m[0;34m,[0m [0;34m**[0m[0moptions[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1062[0m         )
[0;32m-> 1063[0;31m         [0;32mreturn[0m [0mcast[0m[0;34m([0m[0mResponseT[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mrequest[0m[0;34m([0m[0mcast_to[0m[0;34m,[0m [0mopts[0m[0;34m,[0m [0mstream[0m[0;34m=[0m[0mstream[0m[0;34m,[0m [0mstream_cls[0m[0;34m=[0m[0mstream_cls[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1064[0m [0;34m[0m[0m
[1;32m   1065[0m     def patch(

[0;32m~/miniforge3/lib/python3.9/site-packages/openai/_base_client.py[0m in [0;36mrequest[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)[0m
[1;32m    840[0m         [0mstream_cls[0m[0;34m:[0m [0mtype[0m[0;34m[[0m[0m_StreamT[0m[0;34m][0m [0;34m|[0m [0;32mNone[0m [0;34m=[0m [0;32mNone[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    841[0m     ) -> ResponseT | _StreamT:
[0;32m--> 842[0;31m         return self._request(
[0m[1;32m    843[0m             [0mcast_to[0m[0;34m=[0m[0mcast_to[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    844[0m             [0moptions[0m[0;34m=[0m[0moptions[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/openai/_base_client.py[0m in [0;36m_request[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)[0m
[1;32m    883[0m             [0;31m# to completion before attempting to access the response text.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    884[0m             [0merr[0m[0;34m.[0m[0mresponse[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 885[0;31m             [0;32mraise[0m [0mself[0m[0;34m.[0m[0m_make_status_error_from_response[0m[0;34m([0m[0merr[0m[0;34m.[0m[0mresponse[0m[0;34m)[0m [0;32mfrom[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    886[0m         [0;32mexcept[0m [0mhttpx[0m[0;34m.[0m[0mTimeoutException[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    887[0m             [0;32mif[0m [0mretries[0m [0;34m>[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAuthenticationError[0m: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-.... You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-.... You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

