Traceback (most recent call last):
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/victorgallego/miniforge3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/victorgallego/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

deployment = replicate.deployments.get("vicgalle/image-blending")
prediction = deployment.predictions.create(
  input={"image1": open("images/deer.png", "rb"),
         "image2": open("images/clock.png", "rb"),
         "prompt": ""}
)
prediction.wait()
print(prediction.output)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mReplicateError[0m                            Traceback (most recent call last)
[0;32m/var/folders/l_/k13w4mhd5hv4bddxwqz8qdfw0000gn/T/ipykernel_6609/1154814429.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mdeployment[0m [0;34m=[0m [0mreplicate[0m[0;34m.[0m[0mdeployments[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"vicgalle/image-blending"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m prediction = deployment.predictions.create(
[0m[1;32m      3[0m   input={"image1": open("images/deer.png", "rb"),
[1;32m      4[0m          [0;34m"image2"[0m[0;34m:[0m [0mopen[0m[0;34m([0m[0;34m"images/clock.png"[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m          "prompt": ""}

[0;32m~/miniforge3/lib/python3.9/site-packages/replicate/deployment.py[0m in [0;36mcreate[0;34m(self, input, **params)[0m
[1;32m    127[0m         [0mbody[0m [0;34m=[0m [0m_create_prediction_body[0m[0;34m([0m[0mversion[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0minput[0m[0;34m=[0m[0minput[0m[0;34m,[0m [0;34m**[0m[0mparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    128[0m [0;34m[0m[0m
[0;32m--> 129[0;31m         resp = self._client._request(
[0m[1;32m    130[0m             [0;34m"POST"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    131[0m             [0;34mf"/v1/deployments/{self._deployment.owner}/{self._deployment.name}/predictions"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/replicate/client.py[0m in [0;36m_request[0;34m(self, method, path, **kwargs)[0m
[1;32m     83[0m     [0;32mdef[0m [0m_request[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mmethod[0m[0;34m:[0m [0mstr[0m[0;34m,[0m [0mpath[0m[0;34m:[0m [0mstr[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m [0;34m->[0m [0mhttpx[0m[0;34m.[0m[0mResponse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     84[0m         [0mresp[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_client[0m[0;34m.[0m[0mrequest[0m[0;34m([0m[0mmethod[0m[0;34m,[0m [0mpath[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 85[0;31m         [0m_raise_for_status[0m[0;34m([0m[0mresp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     86[0m [0;34m[0m[0m
[1;32m     87[0m         [0;32mreturn[0m [0mresp[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/replicate/client.py[0m in [0;36m_raise_for_status[0;34m(resp)[0m
[1;32m    356[0m [0;32mdef[0m [0m_raise_for_status[0m[0;34m([0m[0mresp[0m[0;34m:[0m [0mhttpx[0m[0;34m.[0m[0mResponse[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    357[0m     [0;32mif[0m [0;36m400[0m [0;34m<=[0m [0mresp[0m[0;34m.[0m[0mstatus_code[0m [0;34m<[0m [0;36m600[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 358[0;31m         [0;32mraise[0m [0mReplicateError[0m[0;34m([0m[0mresp[0m[0;34m.[0m[0mjson[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0;34m"detail"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mReplicateError[0m: You did not pass a valid authentication token
ReplicateError: You did not pass a valid authentication token

